require('node:fs').mkdirSync(require('node:path').resolve(__dirname,'../.test-results'),{recursive:true});
const {chromium}=require('playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),results=[];
const wav=Buffer.alloc(44+16000*60);wav.write('RIFF');wav.writeUInt32LE(wav.length-8,4);wav.write('WAVEfmt ',8);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(8000,24);wav.writeUInt32LE(16000,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(wav.length-44,40);
const source='data:audio/wav;base64,'+wav.toString('base64');
(async()=>{
const browser=await chromium.launch({channel:process.env.ANCHOR_BROWSER?undefined:'chromium',executablePath:process.env.ANCHOR_BROWSER||undefined,headless:true,args:['--autoplay-policy=no-user-gesture-required']});const page=await browser.newPage();
await page.route('https://media.test/**',r=>r.fulfill({contentType:'text/html',body:`<!doctype html><html><body><video id="video" src="${source}"></video></body></html>`}));
await page.addInitScript(()=>{window.callbacks={};const session=navigator.mediaSession,original=session.setActionHandler.bind(session);session.setActionHandler=(action,handler)=>{callbacks[action]=handler;return original(action,handler);};});
await page.goto('https://media.test/player');await page.waitForFunction(()=>video.readyState>=2);
await page.addScriptTag({content:fs.readFileSync(path.join(root,'main.js'),'utf8')});
const configure=enabled=>page.evaluate(enabled=>document.dispatchEvent(new CustomEvent('pause-keeper:command',{detail:JSON.stringify({command:'configure',config:{enabled}})})),enabled);
const action=type=>page.evaluate(type=>callbacks[type]({action:type}),type);
const paused=()=>page.evaluate(()=>video.paused);
const test=async(name,fn)=>{try{await fn();results.push({name,passed:true});console.log('PASS',name);}catch(e){results.push({name,passed:false,error:e.stack});console.error('FAIL',name,e.stack);}};
try{
await test('Fallback Media Session handlers exist when the site supplies none',async()=>{await configure(true);assert.deepEqual(await page.evaluate(()=>['play','pause','stop'].map(a=>typeof callbacks[a])),['function','function','function']);});
await test('OS Play starts the default player and OS Pause holds it',async()=>{await action('play');await page.waitForFunction(()=>!video.paused);await action('pause');assert.equal(await paused(),true);assert.equal(await page.evaluate(()=>video.play().then(()=>false,e=>e.name)),'NotAllowedError');assert.equal(await page.evaluate(()=>navigator.mediaSession.playbackState),'paused');});
await test('OS Play releases an existing pause latch',async()=>{await action('play');await page.waitForFunction(()=>!video.paused);assert.equal(await page.evaluate(()=>navigator.mediaSession.playbackState),'playing');});
await test('Site-specific Play and Pause callbacks are preserved and run once',async()=>{await page.evaluate(()=>{window.counts={play:0,pause:0};window.sitePlay=()=>{counts.play++;video.play().catch(()=>{});};window.sitePause=()=>{counts.pause++;video.pause();};navigator.mediaSession.setActionHandler('play',sitePlay);navigator.mediaSession.setActionHandler('pause',sitePause);});await action('pause');await action('play');await page.waitForFunction(()=>!video.paused);assert.deepEqual(await page.evaluate(()=>counts),{play:1,pause:1});});
await test('Removing a site handler leaves the generic hardware fallback',async()=>{await page.evaluate(()=>navigator.mediaSession.setActionHandler('play',null));await action('pause');await action('play');await page.waitForFunction(()=>!video.paused);});
await test('A broken or no-op site Play handler recovers through the fallback',async()=>{await page.evaluate(()=>navigator.mediaSession.setActionHandler('play',()=>{throw Error('broken site callback');}));await action('pause');await action('play');await page.waitForFunction(()=>!video.paused);});
await test('A newer Pause cancels delayed Play recovery',async()=>{await page.evaluate(()=>navigator.mediaSession.setActionHandler('play',()=>{}));await action('pause');await action('play');await action('pause');await page.waitForTimeout(450);assert.equal(await paused(),true);assert.equal(await page.evaluate(()=>video.play().then(()=>false,e=>e.name)),'NotAllowedError');});
await test('OS Stop is a persistent pause without losing the viewing position',async()=>{await action('play');await page.waitForFunction(()=>!video.paused);await page.evaluate(()=>video.currentTime=12);await action('stop');assert.equal(await paused(),true);assert.equal(Math.round(await page.evaluate(()=>video.currentTime)),12);});
await test('Disabling restores original site callbacks and playbackState',async()=>{await page.evaluate(()=>{navigator.mediaSession.setActionHandler('play',sitePlay);navigator.mediaSession.setActionHandler('pause',sitePause);});await configure(false);assert.equal(await page.evaluate(()=>callbacks.play===sitePlay&&callbacks.pause===sitePause),true);assert.equal(await page.evaluate(()=>navigator.mediaSession.playbackState),'none');assert.equal(await page.evaluate(()=>callbacks.stop),null);await page.evaluate(()=>video.play());assert.equal(await paused(),false);});
await test('Removing the player unregisters Anchor fallback callbacks',async()=>{await page.evaluate(()=>{navigator.mediaSession.setActionHandler('play',null);navigator.mediaSession.setActionHandler('pause',null);});await configure(true);await page.evaluate(()=>video.remove());await page.waitForTimeout(150);assert.equal(await page.evaluate(()=>callbacks.play===null&&callbacks.pause===null&&callbacks.stop===null),true);});
}finally{fs.writeFileSync(path.join(root,process.env.ANCHOR_BROWSER?'.test-results/brave-media-session-test-results.json':'.test-results/media-session-test-results.json'),JSON.stringify({note:'Real browser Media Session registration; action callbacks exercised through a recording shim.',tests:results},null,2));await browser.close();}if(results.some(r=>!r.passed))process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1;});
